apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-secret
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: contato@patrickalmeida.com
    privateKeySecretRef:
      name: letsencrypt-tls
    solvers:
    - http01:
        ingress:
          name: ingress-host