apiVersion: v1
kind: Service
metadata:
  name: goserver-service
spec:
  selector:
    app: goserver
  type: NodePort # by default we have: ClusterIP, NodePort, LoadBalancer and Headless
  ports:
    - name: goserver-service
      port: 80 # service port
      targetPort: 8000 # server.go and docker exported port
      protocol: TCP
      nodePort: 30001 # port which nodeport will expose in all nodes 